gcc/config/epiphany: Fix ICE on movcc
Fix errors of this form:

LRA (-mlra):

20000717-1.c:11:1: error: unable to generate reloads for:
(insn 80 69 70 4 (parallel [
            (set (reg:CC 113)
                (reg:CC 123 [113]))
            (use (const_int -4337 [0xffffef0f]))
            (clobber (reg:SI 124))
        ]) "20000717-1.c":8:19 49 {*movcc_i}

Reload:

20000427-1.c:9:1: error: unrecognizable insn:
(insn 65 55 56 2 (parallel [
            (set (mem/c:CC (plus:SI (reg/f:SI 15 fp)
                        (const_int -28 [0xffffffe4])) [2 %sfp+-12 S4 A32])
                (reg:CC 0 r0))
            (use (const_int -4337 [0xffffef0f]))
            (clobber (scratch:SI))
        ]) -1
     (nil))

gcc/ChangeLog.epiphany:

	* config/epiphany/epiphany.md (movcc): Convert non-CC_REGNUM
	register-register moves to SI to break lra loop.
	(movcc_i): Fix length attribute.
	(movcc_i2): New pattern. Recognize memory-register CCmode moves.

Signed-off-by: Ola Jeppsson <ola.jeppsson@gmail.com>